#! /bin/bash

# all alan"s aliases
#   as ordered by strcmp()

# One quote might help in reading these files:
#   "If in doubt, call it Fred", Dr. Mike Scott, Dublin City University, late 80s

# This list is quite long enough, we accept no other aliases
#   Thanks anyway
unalias -a 

# The wee x headings are counts
#   all the wee aliases in this wee section have only one character, oui,
#       Awwww.
#   There is an alias for every letter
#       albeit most are unused

# x

alias -- -="c -"
alias 1=todo_edit
alias 2=todo_show
alias 3=Tree
alias a="ack"
alias b="b"
# c is a function
alias d="d"
alias e="ex --noplugin -u ~/.vim/exrc"
# f is a function
alias g="grep --color"
# h is a function
alias i="i"
alias j="j"
alias k="k"
alias l="$LS_PROGRAM "
alias m="m"
alias n="n"
alias o="o"
# p is a function
# q is a function
alias Q="exit 0"
alias r="rm -vrf"
alias s="s"
alias t="t"
alias u="u"
# v is a function
# w is a function
# x is a function
# y is a function
alias z="du -sh"

# xx

alias ..='c ..'

alias eg="env | g "

alias jj="c $JAB"

alias kp="rsync -a"

alias ls="$LS_PROGRAM $LS_COLOUR_OPTION $LS_DIRS_OPTION"

alias p-="echo $OLDPWD"
alias pc="python -c"
alias pt="p $JAB_PYTHON/vim_traceback.py"

alias r.="rm -rvf *"
alias rq="rm -rf "

alias sa="source_aliases $JAB/aliases"
alias sb="c $JAB && source bashrc && -"
alias se="source $JAB/environ"
alias sf="source $JAB/functons"
alias sp="source $JAB/prompt"
alias sr="sudo rm -vrf "

alias xk="exchange_keys"

alias yy="y $PYTHON_HOME"

alias z.="zm \*"

# xxx

alias ..l='cl ..'
alias ...='c ../..'

alias doc="c ~/Documents"

alias clx="cl; lx "
alias cly="cl; ly "
alias csi='c $(python -c "import sys; print [p for p in sys.path if p.endswith(\"site-packages\")][0]")'

alias jlf="sst jlfieblu jlf.ie"

alias kpp="kp --progress"

alias lda="ls -1da"
alias lff="ls fred*"
alias lll="ll -a"
alias lra="lr -a"
alias lrd="lr -d"
alias lsh="ls *.sh"

alias out="to_release"

alias sla="source $JAB/local/aliases"
alias sle="source $JAB/local/environ"
alias slf="source $JAB/local/functons"
alias slp="source $JAB/local/prompt"
alias spe="source $JAB/python-environ"

alias tra="try ~/alans_tests"

alias vin="vim -"

alias url="python ~/bin/show_url.py "

# xxxx

alias ....='c ../../..'

alias comp="source $JAB/company-environment"

alias home="cd; cls"

alias tags="p $JAB_PYTHON/ptags.py "


# xxxxx

alias .....='c ../../../..'

alias ptags="p $JAB_PYTHON/ptags.py "

# xxxxxx

alias ......='c ../../../../..'

alias lessen="less -N"


# xxxxxxx

alias .......='c ../../../../../..'
alias service="sudo /sbin/service "

# xxxxxxxx

# xxxxxxxx

alias stopwatch="killall -9 watch"

alias update_hosts="sudo python $JAB_PYTHON/update_hosts.py"
