#! /bin/sh

# all alan"s aliases
# 	as ordered by strcmp()

# One quote might help in reading these files:
# 	"If in doubt, call it Fred", Dr. Mike Scott, Dublin City University, late 80s

# This list is quite long enough, we accept no other aliases
#	Thanks anyway
unalias -a 

# The wee x headings are counts
# 	all the wee aliases in this wee section have only one character, oui,
#		Awwww.
#   There is an alias for every letter except y
#		albeit some are unused

# x

alias -- -="c -"
alias 1="v $JAB_TODO"
alias 2="python2.7 $JAB/python/todo.py"
alias 3="tree"
alias 7="svn"
alias a="a"
alias b="b"
alias c="kd "
alias d="d"
alias e="ex --noplugin -u ~/.vim/exrc"
alias f="find "
alias g="grep --color"
alias h="history | tail -n 25"
alias i="i"
alias j="j"
alias k="k"
alias l="$LS_PROGRAM "
alias m="m"
alias n="n"
alias o="o"
# p is a function
alias q="exit 0"
alias Q="exit 0"
alias r="rm -vrf"
alias s="s"
alias t="t"
alias u="u"
alias v="$JAB/bin/fim "
alias w="which "
alias x="x"
alias y='clear; p $JAB/python/y.py '
alias z="du -sh"

# xx

alias ..='c ..'

alias 3l="tree | less"

alias aa="ack --all"
alias ab="ssh abrogan@192.168.0.103"
alias ap="ack --python"
alias at="ack --pyt"

alias cy="c \$PYTHON_HOME"

alias eg="env | grep "

alias gh="history | grep "
alias in="to_source"

alias jj="c $JAB"

alias kp="rsync -av"

alias la="ls -a "
alias lj="ls $JAB"
alias ll="ls -lh "
alias lr="ls -lhtr"
alias ls="$LS_PROGRAM $LS_COLOUR_OPTION $LS_DIRS_OPTION"
alias lt="ls *.test*"
alias lx="p $JAB/python/ls/lx.py "
alias ly="p $JAB/python/ls/ly.py "

alias p-="echo $OLDPWD"
alias pi="ipython "

alias r.="rm -rvf *"
alias rq="rm -rf "
alias rs="sudo -i -u svn"
alias ry="rf pycos"

alias sa="source $JAB/aliases"
alias sb="cd $JAB && source bashrc && -"
alias sc="svn ci -m"
alias sd="sdiff "
alias se="source $JAB/environ"
alias sf="source $JAB/functons"
alias si="svn_info "
alias sl="svn_log "
alias so="sort "
alias sp="source $JAB/prompt"
alias sr="svn resolved "
alias sv="svn revert "
alias st="stat "

alias tf="tail -f"

alias v.="v ."
alias va="v $JAB/aliases; sa"
alias vb="v $JAB/bashrc; sb"
alias vd="vim -do "
alias ve="v $JAB/environ; se"
alias vf="v $JAB/functons; sf"
alias vh="v ~/.bash_history +"
alias vj="v $JAB"
alias vp="v $JAB/prompt; sp"
alias vt="v -p *.txt"
alias vv="v $JAB/bin/fim"
alias vy="v $PYTHON_HOME"

alias xk="exchange_keys"

alias yy="y $PYTHON_HOME"

alias z.="zm \*"

# xxx

alias ...='c ../..'

alias 7up='svn up'

alias doc="cd ~/Documents"

alias clx="cl; lx "
alias cly="cl; ly "

alias jab="ssh jab@pinky"
alias jjy="ky $JAB/python"
alias jlf="ssh jlfieblu@jlf.ie"

alias lff="ls fred*"
alias lsh="ls *.sh"

alias out="to_release"

alias ps3="ps axjf | vim - +"

alias rq.="/bin/rm -rf ./*"
alias rff="r fred* *.tmp"

alias sib=". ~/.bashrc"
alias sii="svn_issue "

alias shd='svn_diff "vimdiff -o" '
alias skd="svn_diff kdiff "
alias sla="source $JAB/local/aliases"
alias sle="source $JAB/local/environ"
alias slf="source $JAB/local/functons"
alias sli="svn_log_issue"
alias slp="source $JAB/local/prompt"
alias spe="source $JAB/python-environ"
alias stj="statvim $JAB"
alias stm="statvim | grep -v ^r"
alias stv="statvim "
alias svd="svn_diff vimdiff "
alias sxd="svn_diff xdiff "

alias tra="try ~/alans_tests"

alias vib="v ~/.bashrc; sib"
alias vla="v $JAB/local/aliases; sla"
alias vlb="v $JAB/local/bashrc; slb"
alias vle="v $JAB/local/environ; sle"
alias vlf="v $JAB/local/functons; slf"
alias vlp="v $JAB/local/prompt; slp"
alias vpe="v $JAB/python-environ; spe"
alias vvv="v $JAB/vim"

alias url="python ~/bin/show_url.py "

# xxxx

alias ....='c ../../..'

alias alto="source $JAB/altobridge-environment"

alias cdsi="cd /usr/lib/python2.4/site-packages"

alias down="cd ~/Download"

alias mine="sudo chown $USER:allstaff "

alias jjya='ky $JAB/python/alanology'
alias jjys='ky $JAB/python/site'
alias junk="mount ie-serv-2.altobridge.com:/export/junk /Users/shared/alto/junk"

alias rias="ssh abrogan@172.20.1.172"

alias tags="p $JAB/python/ptags.py "

alias vvvv="v $JAB/vim/vimrc"

# xxxxx

alias .....='c ../../../..'

alias ptags="p $JAB/python/ptags.py "

alias sdiff="svn_diff diff "

# xxxxxx

alias ......='c ../../../../..'

alias build2="ssh abrogan@ie-build-2"
alias lessen="less -N"

alias zimbra='mutt -f imap://abrogan:AlrB3@1@@ie-mail-1.altobridge.com/'

# xxxxxxx

alias .......='c ../../../../../..'
alias abrogan="ssh abrogan@192.168.0.103"
alias service="sudo /sbin/service "
alias cleaner="clean deep"

# xxxxxxxx

alias cleanest="clean deep pycos"

# xxxxxxxx

alias stopwatch="killall -9 watch"
