#! /bin/sh

# all alan"s aliases
# 	as ordered by strcmp()

# One quote might help in reading these files:
# 	"If in doubt, call it Fred", Dr. Mike Scott, Dublin City University, late 80s

# This list is quite long enough, we accept no other aliases
#	Thanks anyway
unalias -a 

# The wee x headings are counts
# 	all the wee aliases in this wee section have only one character, oui,
#		Awwww.
#   There is an alias for every letter except y
#		albeit some are unused

# x

alias -- -='kd - >/dev/null 2>&1'
alias 1="v $JAB/todo.txt"
alias 2="cat $JAB/todo.txt"
alias a="a"
alias b="b"
alias c="kd "
alias d="d"
alias e="e"
alias f="find "
alias g="grep --color"
alias h="history | tail -n 25"
alias i="i"
alias j="j"
alias k="k"
alias l="/bin/ls "
alias m="m"
alias m="mount ie-build-1:/mnt/releases /Users/shared/alto/releases"
alias n="n"
alias o="o"
# p is a function
alias q="exit 0"
alias r="rm -vrf"
alias s="s"
alias t="t"
alias u="u"
alias v="$JAB/bin/fim "
alias w="which "
alias x="x"
alias y='clear; p $JAB/python/y.py '
alias z="du -sh"

# xx

alias ..='kd ..'

alias ab="ssh abrogan@192.168.0.103"

alias c-='kd - >/dev/null 2>&1'
alias cb='kd ~/bin'
alias cl='clear'
alias cy="kd \$MAIN_PYTHON"

alias eg="env | grep "

alias gh="history | grep "
alias in="to_source"

alias jj="kd $JAB"

alias la="ls -a "
alias lj="ls $JAB"
alias ll="ls -lh "
alias ls="l $LS_COLOUR_OPTION "
alias lt="ls *.test*"
alias lx="p $JAB/python/ls/lx.py "
alias ly="p $JAB/python/ls/ly.py "

alias p-="echo $OLDPWD"
alias pi="ipython "
alias py="y $MAIN_PYTHON"

alias ra="sudo -i -u abrogan"
alias rb="sudo -i -u builder"
alias rq="/bin/rm -rf "
alias rs="sudo -i -u svn"
alias ry="rf pycos"

alias sa="source $JAB/aliases"
alias sb="cd $JAB && source bashrc && c-"
alias sc="svn ci -m"
alias sd="sdiff "
alias se="source $JAB/environ"
alias sf="source $JAB/functons"
alias si="svn_info "
alias sl="svn_log "
alias so="sort "
alias sp="source $JAB/prompt"
alias sr="svn resolved "
alias sv="svn revert "
alias st="stat "

alias v.="v ."
alias va="v $JAB/aliases; sa"
alias vb="v $JAB/bashrc; sb"
alias vd="vim -do "
alias ve="v $JAB/environ; se"
alias vf="v $JAB/functons; sf"
alias vj="v $JAB"
alias vp="v $JAB/prompt; sp"
alias vt="v -p *.txt"
alias vv="v $JAB/bin/fim"
alias vy="v $MAIN_PYTHON"

alias xk="exchange_keys"

alias yy="y $MAIN_PYTHON"

# xxx

alias ...='kd ../..'
alias c--="cd -"

alias clx="cl; lx "
alias cly="cl; ly "

alias jjy='ky $JAB/python'
alias jlf="ssh jlfieblu@jlf.ie"

alias lff="ls fred*"
alias lsh="ls *.sh"

alias out="to_release"

alias ps3="ps axjf | vim -"

alias rqa="/bin/rm -rf ./*"
alias rff="r fred*"

alias sib=". ~/.bashrc"
alias sii="svn_issue "

alias shd='svn_diff "vimdiff -o" '
alias skd="svn_diff kdiff "
alias sla="source $JAB/local/aliases"
alias sle="source $JAB/local/environ"
alias slf="source $JAB/local/functons"
alias slp="source $JAB/local/prompt"
alias spe="source $JAB/python-environ"
alias sta="statvim | sed -e s/^r/svn\ add/"
alias stj="statvim $JAB"
alias stv="statvim "
alias svd="svn_diff vimdiff "
alias sxd="svn_diff xdiff "


alias tra="try ~/alans_tests"

alias vbb="v \$BUILDER_WORKING/build.py"
alias vib="v ~/.bashrc; sib"
alias vla="v $JAB/local/aliases; sla"
alias vlb="v $JAB/local/bashrc; slb"
alias vle="v $JAB/local/environ; sle"
alias vlf="v $JAB/local/functons; slf"
alias vlp="v $JAB/local/prompt; slp"
alias vpe="v $JAB/python-environ; spe"
alias vvv="v $JAB/vim"

alias url="python ~/bin/show_url.py "

# xxxx

alias ....='kd ../../..'

alias cdsi="cd /usr/lib/python2.4/site-packages"
alias cdev="cd ~/jab/alto/dev"

alias down="cd ~/Download"

alias mine="sudo chown $USER:allstaff "

alias jjya='kd $JAB/python/alanology'
alias jjys='kd $JAB/python/site'
alias junk="mount ie-serv-2.altobridge.com:/export/junk /Users/shared/alto/junk"

alias tags="p $JAB/python/ptags.py "

alias vvvv="v $JAB/vim/vimrc"

# xxxxx

alias .....='kd ../../../..'

alias cisco="ru /System/Library/StartupItems/CiscoVPN/CiscoVPN restart"

alias floka="get_pinky_ip && ssh floka@${pinky_ip}"

alias ptags="p $JAB/python/ptags.py "

alias sdiff="svn_diff diff "

# xxxxxx

alias ......='kd ../../../../..'

alias build2="ssh abrogan@ie-build-2"
alias lessen="less -N"
alias public="mount ie-file-1.altobridge.com:/export/public /Users/shared/alto/public"

alias zimbra='mutt -f imap://abrogan:alrb3002@ie-mail-1.altobridge.com/'

# xxxxxxx

alias .......='kd ../../../../../..'
alias abrogan="ssh abrogan@192.168.0.103"
alias service="sudo /sbin/service "
alias cleaner="clean deep"
alias roundup="roundup-admin -i /usr/local/trackers/tracker -u $USER:alrb3002"

# xxxxxxxx

alias cleanest="clean deep pycos"

# xxxxxxxx

alias stopwatch="killall -9 watch"
