#! /bin/bash

# Load an Altobridge environment

if [[ -d /Users/jab/jab/alto/dev/friday/tracking ]]
then TRACKERS=/Users/jab/jab/alto/dev/friday/tracking
elif [[ -d /usr/local/trunk/trackers ]]
then TRACKERS=$(readlink -f /usr/local/trunk/trackers)
elif [[ -d /mnt/source/amg/trunk/trackers ]]
then TRACKERS=$(readlink -f /mnt/source/amg/trunk/trackers)
elif [[ -d /data/trackers ]]
then TRACKERS=$(readlink -f /data/trackers)
fi

unset SITE
unset PYTHONPATH

if [[ -n $TRACKERS ]]
then
	source $TRACKERS/python/source_python_path
	source $TRACKERS/ie-track-1/etc/tracker_environ
	source $TRACKERS/ie-track-1/etc/tracker_functions
	source $TRACKERS/ie-track-1/etc/tracker_aliases
else
	echo Could not find a trackers checkout
fi

if [[ -d /Users/jab/jab/alto/ ]]
then
	cd /Users/jab/jab/alto/alto_python
	source bin/activate
	cd - > /dev/null 2>&1
fi
