#! /bin/bash

# Load an Altobridge environment

if [[ -z $TRACKERS ]]
then 
	if [[ -d /Users/jab/jab/alto/dev/friday/trackers ]]
	then TRACKERS=/Users/jab/jab/alto/dev/friday/trackers
	elif [[ -d /Users/jab/jab/alto/dev/friday/tracking ]]
	then TRACKERS=/Users/jab/jab/alto/dev/friday/tracking
	elif [[ -d /usr/local/trunk/trackers ]]
	then TRACKERS=$(readlink -f /usr/local/trunk/trackers)
	elif [[ -d /mnt/source/amg/trunk/trackers ]]
	then TRACKERS=$(readlink -f /mnt/source/amg/trunk/trackers)
	elif [[ -d /data/trackers ]]
	then TRACKERS=$(readlink -f /data/trackers)
	fi
fi

unset SITE
unset PYTHONPATH

if [[ -n $TRACKERS ]]
then
	source $TRACKERS/python/source_python_path
	source $TRACKERS/ie-track-1/etc/tracker_environ
	source $TRACKERS/ie-track-1/etc/tracker_functions
	source $TRACKERS/ie-track-1/etc/tracker_aliases
	cd $TRACKERS
	export IGNORE_CHANGES=1
else
	echo Could not find a trackers checkout
fi

if [[ -d /Users/jab ]]  # looks like a mac book
then
	USER=abrogan
	if [[ $1 != "local" ]]
	then
		if ! ping -c 1 -t 1 ie-track-1.altobridge.com >/dev/null 2>&1 
		then
			echo Cannot contact ie-track-1.altobridge.com
		else
			/bin/bash ~/bin/mount_alto track
		fi
	fi
	if [[ -f $JAB/python/pythonrc.py ]]
	then PYTHONSTARTUP=$JAB/python/pythonrc.py
	elif [[ -f ~/.pythonrc.py ]]
	then [[ PYTHONSTARTUP=~/.pythonrc.py ]]
	fi
fi
