#! /bin/sh

export JAB=$HOME/.jab
export JAB_TODO=$JAB/todo.txt

export COLUMNS

export EXITSTATUS="$?"
export FIGNORE=.pyc:.swp:~:.o

#export DISPLAY=:0

# infinite history (was claimed - in practice it keeps very short histories)
# unset HISTSIZE
# unset HISTFILESIZE
# So we explicitly keep very large histories
export HISTFILESIZE=100000
export HISTSIZE=$HISTFILESIZE
# format history times
export HISTTIMEFORMAT="%h/%d - %H:%M:%S "
# ignore some simple commands in history
export HISTIGNORE="bg:fg:history:gh:hh"
#  remember multi-line commands
shopt -s cmdhist
# edit a failed history substitution (default just ignores them)
shopt -s histreedit
# edit history line before executing
shopt -s histverify 
# save multi-line commands to history with "\n", not ":"
shopt -s lithist
# Make bash check its window size after a process completes
shopt -s checkwinsize
# append to the history file, don't overwrite it
shopt -s histappend
# correct minor spelling errors for cd
shopt -s cdspell
#
# some interesting paths
#
export LOGS=/var/log
export XAUTHORITY=$HOME/.Xauthority

if [[ -f /usr/local/bin/gls ]]
then
	LS_PROGRAM=/usr/local/bin/gls
else
	LS_PROGRAM=/bin/ls
fi

if $LS_PROGRAM -@ >/dev/null 2>&1 
then
	export LS_COLOUR_OPTION='-@'
elif $LS_PROGRAM --color=auto >/dev/null 2>&1
then
	export LS_COLOUR_OPTION='--color=auto'
else
	export LS_COLOUR_OPTION=
fi
if $LS_PROGRAM --group-directories-first >/dev/null 2>&1
then
	export LS_DIRS_OPTION='--group-directories-first'
else
	export LS_DIRS_OPTION=
fi

add_to_a_path PATH /bin
add_to_a_path PATH /usr/bin
add_to_a_path PATH /usr/local/bin
add_to_a_path PATH /usr/local/sbin
add_to_a_path PATH $JAB/bin
add_to_a_path PATH ~/bin
add_to_a_path PATH ~/git/bin
add_to_a_path PATH /opt/local/bin
add_to_a_path PATH /sbin 

export PS1

#
# Path dependencies
#

if [ -d /usr/local/abrogan/jabs ]
then
	export JABS=file:///usr/local/abrogan/jabs
else
	export JABS=http://intranet.altobridge.com/jab
fi

if [ -x /usr/local/bin/which ]
then
	export WHICH=/usr/local/bin/which
else
	export WHICH=/usr/bin/which
fi
export EDITOR=`$WHICH vim`
export EMAIL="al@al-got-rhythm.net"

#
# colours
#
# http://en.wikipedia.org/wiki/ANSI_escape_sequences#Colors
#
export          NO_COLOUR="\[\033[0m\]"
export                RED="\[\033[0;31m\]"
export          LIGHT_RED="\[\033[1;31m\]"
export              GREEN="\[\033[0;32m\]"
export        LIGHT_GREEN="\[\033[1;32m\]"
export              BROWN="\[\033[0;33m\]"
export             YELLOW="\[\033[1;33m\]"
export               BLUE="\[\033[0;34m\]"
export         LIGHT_BLUE="\[\033[1;34m\]"
export            MAGENTA="\[\033[0;35m\]"
export      LIGHT_MAGENTA="\[\033[1;35m\]"
export               CYAN="\[\033[0;36m\]"
export         LIGHT_CYAN="\[\033[1;36m\]"
export              WHITE="\[\033[1;37m\]"
export         LIGHT_GRAY="\[\033[0;37m\]"
export                FOO="\[\033[1;38m\]"
export            FOO_TOO="\[\033[0;38m\]"
export                SED="\[\033[1;39m\]"
export            SED_TOO="\[\033[0;39m\]"
export     PROMPT_NO_COLOUR="\033[0m"
export           PROMPT_RED="\033[0;31m"
export     PROMPT_LIGHT_RED="\033[1;31m"
export         PROMPT_GREEN="\033[0;32m"
export   PROMPT_LIGHT_GREEN="\033[1;32m"
export         PROMPT_BROWN="\033[0;33m"
export        PROMPT_YELLOW="\033[1;33m"
export          PROMPT_BLUE="\033[0;34m"
export    PROMPT_LIGHT_BLUE="\033[1;34m"
export       PROMPT_MAGENTA="\033[1;35m"
export PROMPT_LIGHT_MAGENTA="\033[0;35m"
export          PROMPT_CYAN="\033[0;36m"
export    PROMPT_LIGHT_CYAN="\033[1;36m"
export         PROMPT_WHITE="\033[1;37m"
export    PROMPT_LIGHT_GRAY="\033[0;37m"
export           PROMPT_FOO="\033[1;38m"
export       PROMPT_FOO_TOO="\033[0;38m"

RE_IP="\<\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\>"

set -o vi
