#! /bin/sh

export JAB=$HOME/.jab

export COLUMNS

export EXITSTATUS="$?"
export FIGNORE=.pyc:.swp:~:.o

#export DISPLAY=:0

export HISTSIZE=100000
export HISTTIMEFORMAT="%h/%d - %H:%M:%S "
#  remember multi-line commands
shopt -s cmdhist
# edit a failed history substitution (default just ignores them)
shopt -s histreedit
# edit history line before executing
shopt -s histverify 
# save multi-line commands to history with "\n", not ":"
shopt -s lithist

export XAUTHORITY=$HOME/.Xauthority

if [[ -f /usr/local/bin/gls ]]
then
	LS_PROGRAM=/usr/local/bin/gls
else
	LS_PROGRAM=/bin/ls
fi

if $LS_PROGRAM -@ >/dev/null 2>&1 
then
	export LS_COLOUR_OPTION='-@'
elif $LS_PROGRAM --color=auto >/dev/null 2>&1
then
	export LS_COLOUR_OPTION='--color=auto'
else
	export LS_COLOUR_OPTION=
fi
if $LS_PROGRAM --group-directories-first >/dev/null 2>&1
then
	export LS_DIRS_OPTION='--group-directories-first'
else
	export LS_DIRS_OPTION=
fi

add_to_path ()
{
	if [[ -n "$1" && -d "$1" ]]
	then
		if ! echo $PATH | grep -q "$1"
		then
			export PATH=${PATH}:$1
		fi
	fi
}
export PATH=/bin:/usr/local/bin:/usr/bin:
add_to_path /usr/local/sbin
add_to_path $JAB/bin
add_to_path ~/bin
add_to_path ~/git/bin
add_to_path /opt/local/bin
add_to_path /sbin

export PS1

#
# Path dependencies
#

# Altobridge repositories
if [ -d /amg ]
then
	export AMG=file:///amg
	export LCP=file:///usr/local/svn/lcp
	export JABS=file:///usr/local/abrogan/jabs
else
	export AMG=svn+ssh://ie-track-1/amg
	export LCP=http://intranet.altobridge.com/svn/lcp
	export JABS=http://intranet.altobridge.com/jab
fi
#
# Working directories
#
if [ -d /mnt/source ]
then
	export SOURCE=/mnt/source
	export AMG_SOURCE=/mnt/source/amg
elif [ -d $SITE/altobridge ]
then
	export SOURCE=$SITE/altobridge
else
	export SOURCE=$JAB
fi
if [ -d /usr/local/trunk ]
then
	export AMG_TRUNK=/usr/local/trunk
elif [[ -n "$AMG_SOURCE" && -d "$AMG_SOURCE" ]]
then
	export AMG_TRUNK=$AMG_SOURCE/trunk
else
	export AMG_TRUNK=
fi
if [ -d $AMG_TRUNK ]
then
	export AMG_BUILDS=${AMG_SOURCE}/builds
	export AMG_RELEASES=${AMG_SOURCE}/releases
	export AMG_DISTRIBUTION=${AMG_SOURCE}/distribution
	export AMG_IT=${AMG_SOURCE}/IT
fi

export LCP_SOURCE=$SOURCE/lcp
export NSN_SOURCE=$LCP_SOURCE/nsn
export NSN_BUILDS=${NSN_SOURCE}/builds
export NSN_RELEASES=${NSN_SOURCE}/releases

export RELEASES=/mnt/releases
export BUILDING=${RELEASES}/building
export BUILD_DEBUG=${RELEASES}/building/debug
export NOTES=${RELEASES}/building/notes

if [ -x /opt/local/bin/gwhich ]
then
	export WHICH=/opt/local/bin/gwhich
else
	export WHICH=/usr/bin/which
fi
export EDITOR=`$WHICH vim`

#
# colours
#
export          NO_COLOUR="\[\033[0m\]"
export                FOO="\[\033[0;31m\]"
export          LIGHT_RED="\[\033[1;31m\]"
export              GREEN="\[\033[0;32m\]"
export        LIGHT_GREEN="\[\033[1;32m\]"
export              BROWN="\[\033[0;33m\]"
export             YELLOW="\[\033[1;33m\]"
export               BLUE="\[\033[0;34m\]"
export         LIGHT_BLUE="\[\033[1;34m\]"
export            MAGENTA="\[\033[0;35m\]"
export      LIGHT_MAGENTA="\[\033[1;35m\]"
export               CYAN="\[\033[0;36m\]"
export         LIGHT_CYAN="\[\033[1;36m\]"
export              WHITE="\[\033[1;37m\]"
export         LIGHT_GRAY="\[\033[0;37m\]"
export                RED="\[\033[1;38m\]"
export            RED_TOO="\[\033[0;38m\]"
export                SED="\[\033[1;39m\]"
export            SED_TOO="\[\033[0;39m\]"
export     PROMPT_NO_COLOUR="\033[0m"
export           PROMPT_FOO="\033[0;31m"
export     PROMPT_LIGHT_RED="\033[1;31m"
export         PROMPT_GREEN="\033[0;32m"
export   PROMPT_LIGHT_GREEN="\033[1;32m"
export         PROMPT_BROWN="\033[0;33m"
export        PROMPT_YELLOW="\033[1;33m"
export          PROMPT_BLUE="\033[0;34m"
export    PROMPT_LIGHT_BLUE="\033[1;34m"
export       PROMPT_MAGENTA="\033[1;35m"
export PROMPT_LIGHT_MAGENTA="\033[0;35m"
export          PROMPT_CYAN="\033[0;36m"
export    PROMPT_LIGHT_CYAN="\033[1;36m"
export         PROMPT_WHITE="\033[1;37m"
export    PROMPT_LIGHT_GRAY="\033[0;37m"
export           PROMPT_RED="\033[1;38m"
export       PROMPT_RED_TOO="\033[0;38m"

RE_IP="\<\([0-9]\{1,3\}\.\)\{3\}[0-9]\{1,3\}\>"

set -o vi
