#! /bin/sh

# Called functons because "functions" is ... something else

# sorted by strcmp of function name

# x

y ()
{
# Go to a directory (or here), then scrub, tag, list and stat it
	dir=
	if [ -d "$1" ] 
	then
		dir=`abspath $1`
		shift
	fi
	if [ -z "$dir" ]
	then
		dir=$MAIN_PYTHON
	fi
	if [[ $dir != `abspath` ]]
	then
		cd $dir
	fi
	clear
	rf
	ry
	if [ -x ./clean ]
	then 
		./clean
	fi
	tags
	ly $*
	stat
}

# xx

cj ()
{
# commit jab
	svn ci ~/.jab -m"$*"
}


kd ()
{ 
# cd to filename as well as directory
	cd `python ~/.jab/python/kd.py $*`
	stat 
}

rf ()
{
# Clean one directory
	/bin/rm -vrf *~ .*~ *.orig fred* *.tmp *.bak
	for fail in *.fail
	do
		if [ ! -s $fail ]
		then
			/bin/rm -vrf $fail
		fi
	done
}

ru ()
{
# do da root root route, do da ru !
	if [ -z "$*" ]
	then 
		sudo -i
	else
		sudo $*
	fi
}

uj ()
{
# update jab
	PWD=`pwd`
	if [ $PWD != "$HOME/.jab" ]
	then
		jj
	else
		PWD=
	fi
	. bashrc
	if [ -n $PWD ]
	then
		c-
	fi
}

# xxx

cls ()
{
# clean, clear, ls
	rf
	clear
	if [ -z "$*" ]
	then
	    ls -d `pwd`
	    echo
	fi
	ls $*
}

fsh ()
{
# run fred by his extension
	if [ -f fred.sh ]
	then
		sh fred.sh $*
	elif [ -f fred.py ]
	then
		p fred.py $*
	elif [ -f "fred.test" ]
	then
		try "fred.test" $*
	elif [ -f fred.c ]
	then
		/bin/rm -vf a.out
		gcc fred.c
		if [ -f a.out ]
		then
			./a.out
		fi
	else
		sh fred $*
	fi
}

fpy ()
{
# run fred.py if fred.sh exists
	if [ -f fred.py ]
	then
		p fred.py $*
	fi
}

lly ()
{
	ll *.tests
	echo
	ll *.test
	echo
	ll *.py
}

upj ()
{
# update jab from the repository
	if [[ `svn up ~/.jab | grep -v "At revision" | wc -l` != "0" ]]
	then
		uj
	fi
}

vff ()
{
	FRED=
	found_fred=0
	test -f fred && FRED=fred
	if [[ -n $FRED ]]
	then
		found_fred=1
	fi
	found_wild=0
	for f in fred*[^~]
	do
		test -f $f && found_wild=1
	done
	if [[ $found_fred == 1 && $found_wild == 1 ]]
	then 
		v -p fred fred*[^~]
	elif [[ $found_wild == 1 ]]
	then 
		v -p fred*[^~] 
	else
		v fred
	fi
}

# xxxx

dark ()
{
	svn revert -q ~/.jab/vim/vimrc
}

do_stat ()
{
	test -n "$1" && path=$1 || path="."
	if [[ -f $path || -d $path/.svn ]]
	then
		svn stat $path
	fi
}

stat ()
{
	if [[ -z "$1" ]]
	then
		clean quietly
		do_stat
	else
		for file in $*
		do 
			do_stat $file
		done
	fi
}
# xxxxx

clean ()
{
	if [[ "x$1" == "xpycos" ]]
	then
		REMOVE_PYCOS=true
		shift
	else
		REMOVE_PYCOS=false
	fi
	if [[ "x$1" == "xquietly" ]]
	then
		options=-vrf
		shift
	else
		options=-rf
	fi
	test -n "$1" && dir=$1 || dir="."
	find $dir -name "*~" 			-exec /bin/rm $options {} \;
	find $dir -name ".*~" 			-exec /bin/rm $options {} \;
	find $dir -name "*.fail" -size -1 	-exec /bin/rm $options {} \;
	find $dir -name "fred*" 		-exec /bin/rm $options {} \;
	if $REMOVE_PYCOS
	then
		find $dir -name "*.py[co]" 		-exec /bin/rm $options {} \;
	fi
}

build ()
{
	if [ -d /mnt/source ]
	then 
		ssh builder@ie-build-2
	else
		ssh builder@ie-build-1
	fi
}

kodos ()
{
	pushd /home/builder/Download/ie-build-1/kodos-2.4.9/ >/dev/null
	/usr/bin/python kodos.py &
	popd >/dev/null
}

track ()
{
	if [ -d ~/alans_tests ]
	then
		cd ~/alans_tests
		try
	else
		ssh abrogan@ie-track-1
	fi
}

vfile ()
{
	`echo "$*" | sed -e"s/^File/vim/" | sed -e"s/, line \([0-9]*\).*/ +\1/"`
}

which ()
{ 
	( alias; declare -f ) | \
		$WHICH --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}

# xxxxx

# xxxxxx

bright ()
{
	sed -i -e/color/d ~/.vimrc
}

issues ()
{
	if [ -f $HOME/bin/issues ]
	then
		$HOME/bin/issues $*
	else
		if [ -z "$*" ]
		then
			mysql -u root -D issues 
		else
			mysql -u root -D issues -e $*
		fi
	fi
}

revert ()
{
	cp $1 $1.changed
	svn revert $1
}

# xxxxxxx

svn_log ()
{
	if [ -n "$1" ]
	then
		if [[ -f $1 || -d $1 ]]
		then
			path=$1
			shift 
		fi
	else
		path="."
	fi
	svn log $path | head $*
}

svn_url ()
{
	test -n "$1" && dir=$1 || dir="."
	svn info $dir | grep URL
}

# xxxxxxxx

svn_diff () {
	dir=`dirname $2`
	file=`basename $2`
	pushd "$dir" > /dev/null
	/usr/bin/$1 "$file" .svn/text-base/"$file".svn-base
	popd > /dev/null
}

svn_info ()
{
	test -n "$1" && dir=$1 || dir="."
	svn info $dir 
}

# xxxxxxxxx

svn_issue ()
{
	svn log $* | grep -i "^issue" | head
}

# xxxxxxxxxx

to_source ()
{
	cd $SOURCE/$*
	clear
	ls
}

# xxxxxxxxxx

to_release ()
{
	cd $RELEASES/$*
	clear
	ls
}

# xxxxxxxxxxx

# xxxxxxxxxxxx

get_pinky_ip ()
{
	export pinky_ip=$PINKY_IP
	if [ -r ~/pinky.txt ]
	then
		export pinky_ip=`cat ~/pinky.txt`
	fi
}

