#! /bin/bash

export JAB=${JAB:-$HOME/.jab}
export JAB_TODO=$JAB/todo.txt
home_id=~/.ssh/id_jab
[[ -f $home_id ]] && export JAB_ID=$home_id
export JAB_PUB_ID=$JAB_ID.pub
export JAB_SSH=$(dirname $JAB_PUB_ID)
export JAB_HOME=$HOME
export JAB_PYTHON=$JAB/src/python
export EMPLOYER_DOMAIN=s3group.com
export EMPLOYER_USERNAME=alanb
JABS=
if [ -d /usr/local/svn/jabs ]
then JABS=file:///usr/local/svn/jabs
fi
export JABS
