#! /bin/sh

export PYTHONDOCS=/home/builder/python25/share/doc/html
export SITE=`python -c "import sys; print [ s for s in sys.path if s.endswith('site-packages')][0]"`

export PYTHONPATH=
add_to_pythonpath ()
{
	if [ -d $1 ]
	then
		if [ -z $PYTHONPATH ]
		then
			export PYTHONPATH=$1
		else
			export PYTHONPATH=$PYTHONPATH:$1
		fi
	fi
	if [[ -z $MAIN_PYTHON ]]
	then
		export MAIN_PYTHON=$1
	fi
}
add_to_pythonpath $JAB/python/site
add_to_pythonpath $HOME/python/site
add_to_pythonpath $HOME/jab/python/site
add_to_pythonpath $SITE/altobridge

[[ -f ~/.pythonrc.py ]] &&  export PYTHONSTARTUP=~/.pythonrc.py
