#! /bin/bash

export JAB_PYTHON=$JAB/src/python
source $JAB/bin/add_to_a_path.sh
add_to_a_path PYTHONPATH $JAB_PYTHON/site
export TRY="$JAB_PYTHON/testing/try.py"

test -d $JAB_PYTHON && export PYTHON_HOME=$JAB_PYTHON
test -d ~/src/python && export PYTHON_HOME=~/src/python
test -f $JAB_PYTHON/pythonrc.py && PYTHONSTARTUP=$JAB_PYTHON/pythonrc.py
