#! /bin/bash

find_python () {
    test -x $PYTHON && return 0
    test -n $PYTHON && PYTHON=
    test -f /usr/bin/python && PYTHON=/usr/bin/python
    test -f /usr/local/bin/python && PYTHON=/usr/local/bin/python
    test -f ~/bin/python && PYTHON=~/bin/python
    test -f $JAB/bin/python && PYTHON=$JAB/bin/python
    [[ -n $VIRTUAL_ENV && -f $VIRTUAL_ENV/bin/python ]] && PYTHON=$VIRTUAL_ENV/bin/python
    test -z $PYTHON && PYTHON=$(which python 2>/dev/null)
    test -z $PYTHON && PYTHON=no_python
    export PYTHON
    [[ $PYTHON != no_python ]]
}

find_python

_has_ext () {
  test -n $(ls ${2:-.}/*.$1 | grep -v -e fred -e log  | head -n 1)
}

_has_py () {
    _has_ext py "$@"
}

_try="$_JAB_SRC_PYTHON_DIR/testing/try.py"
[[ -f $_try ]] || _try=no_file_try_py
export TRY=$_try

_jab_src_python_dir=$JAB/src/python
[[ -d $_jab_src_python_dir ]] || _jab_src_python_dir=no_dir_jab_src_python
_home_src_python_dir=~/src/python
[[ -d $_home_src_python_dir ]] || _home_src_python_dir=no_dir_home_src_python

source $JAB/environ  # provides source_path()
source_path $JAB/bin/add_to_a_path.sh

[[ -z $PYTHONPATH ]] && suffix= || suffix=:$PYTHONPATH
[[ $PYTHONPATH =~ $JAB ]] || export PYTHONPATH=$_jab_src_python_dir/site$suffix

export JAB_PYTHON=$_jab_src_python_dir
export HOME_PYTHON=$_home_src_python_dir
_has_py $HOME_PYTHON && add_to_a_path _SRC_PYTHON_PATH $HOME_PYTHON
_has_py $JAB_PYTHON && add_to_a_path _SRC_PYTHON_PATH $JAB_PYTHON
export PYTHON_SOURCE_PATH=$JAB_PYTHON:$HOME_PYTHON
PYTHON_HOME=${HOME_PYTHON:-$JAB_PYTHON}
test -f $PYTHON_HOME/pythonrc.py && export PYTHONSTARTUP=$PYTHON_HOME/pythonrc.py
