#! /bin/bash -x

[[ -n $WELCOME_BYE ]] && echo Welcome to ~/.bashrc on $(hostname -f)

_set_path () {
    LOCAL=/usr/local
    [[ -d $LOCAL/gnu ]] && LOCALS="$LOCAL/gnu:$LOCAL/bin" || LOCALS="$LOCAL/bin"
    BINS=/usr/bin:/bin:/usr/sbin:/sbin
    HOMES=$HOME/bin:$HOME/.local
    export PATH=$LOCALS:$BINS:$HOMES
    export STDOUT=on
    export STDERR=on

    [[ -d $LOCAL/go/bin ]] && PATH=$PATH:$LOCAL/go/bin
}

_bashrc () {
    WELCOME_BYE=
    source ~/jab/__init__.sh
    WELCOME_BYE=
    local _start_dir=$1; shift
    local _jab_dir=~/jab/start_dir
    if [[ -f $_jab_dir ]]; then
        _start_dir=$(cat $_jab_dir)
        rm -f $_jab_dir
    fi
    cd $_start_dir
    export PS1="\$? [\u@\h:\$PWD]\n$ "
    sp
}

vbb () {
    (cd ~/jab
    vim -p ~/.bashrc ~/jab/__init__.sh ~/bashrc.log "$@" +/bash
    ls -l ~/.bashrc ~/jab/__init__.sh ~/bashrc.log)
}

log_main () {
    set -x
    [[ $- =~ i ]] && main > ~/login.log 2>&1
    set +x
    vim ~/login.log +/environ.d.jab.sh
}

_local () {
    source_what ~/jab/local/bashrc optional
}

main () {
    _set_path
    _bashrc ~/jab
    _local
}

# echo bashrc
main  "$@"
# log_main
[[ -n $WELCOME_BYE ]] && echo Bye from ~/.bashrc on $(hostname -f)
