#! /bin/bash -x

lcolour () {
    local colour_="[1;${1}m" no_colour_="[0m"
    local text_="$@"
    printf "$colour_$text_$no_colour_"
}

lred () {
    lcolour 31 "$@"
}

lgreen () {
    lcolour 32 "$@"
}

lblue () {
    lcolour 34 "$@"
}

lwhite () {
    lcolour 37 "$@"
}

lred_user () {
    local _colour_username=$(lblue "${USER:-$(whoami)}")
    local _colour_host=$(lred ${HOSTNAME:-$(hostname -s)})
    echo "${_colour_username}@$_colour_host"
}

export home_user_=~/jab

BASHRC_LOG=~/log/bashrc.log
home_user=$HOME/jab
vbb () {
    local _log=
    test -f $BASHRC_LOG && _log=$BASHRC_LOG
    (
        cd $home_user
        local local_=
        test -f local/__init__.sh && local_=local/__init__.sh
        vim -p ~/.bashrc __init__.sh environ.d/__init__.sh src/bash/__init__.sh $local_ ~/.vimrc $_log "$@"
        readlink -f ~/.bashrc __init__.sh environ.d/__init__.sh src/bash/__init__.sh $local_ ~/.vimrc $_log
    )
    [[ -f $_log ]] && mv $_log ~/log 2>/dev/null
}

vbl () {
    [[ -f $BASHRC_LOG ]] || return 1
    vim $BASHRC_LOG
}

echo_path () {
    echo "PATH is $(echo $PATH | sed -e "s,:,:    ,g" | tr ':' '\n')"
    echo "PSI is $PS1"
    echo "Here is $(readlink -f .)"
}

pre_bashrc_ () {
    local homes_=$home_user/bin:$HOME/bin:$HOME/.local local_=/usr/local
    local locals_="$local_/gnu:$local_/bin:$local_/go/bin"
    local bins_=/usr/bin:/bin:/usr/sbin:/sbin
    local mysite_=/Users/jab/jab/src/python/site/

    local all_="$homes_:$locals_:$bins_"
    PATH=$all_; export PATH
    PYTHONPATH=$mysite_:$PYTHONPATH;

    if test -d $HOME/lib -a -n "$(find $HOME/lib -maxdepth 1 -name 'libpython*' -print -quit)"; then
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib
    fi
}

bashrc_ () {
    # echo_path
    # /usr/bin/say -v Anna Ich möchte eine Maschine, die schreiben kann, wie ich kann &
    export PS1="\$? [$(lred_user)@\h:\$PWD]\n$ "
    local init_=$home_user_/__init__.sh
    [[ -f $init_ ]] && source $init_
    sp green
}

post_bashrc_ () {
    . $home_user/local/__init__.sh optional
}

__main__ () {
    pre_bashrc_
    bashrc_ $home_user
    post_bashrc_
    set +m
}

[[ $- =~ i ]] && __main__  "$@" #  > $BASHRC_LOG 2>&1
