set t_Co=256
" My stuff
"

" Behave like on Windows
"
"
" Keyboard
"
" function keys 
"
 noremap  <F1>      :help<cr>
"noremap  <F2>
"noremap  <F3>
 noremap  <F4>       <c-w>W
"noremap  <F5>
"noremap  <F6>
"noremap  <F7>
 noremap  <F8>      :SeeTab<CR>
 noremap  <F9>      :w!<CR>
"noremap <F10>
 noremap <F11>      :map <F11> 
 noremap <F12>      :map <F12> 

 noremap <S-F4> <C-W>P
nnoremap <C-F4> <C-W>c
"
" ordinary keys 
"
" letters
"
"noremap a - append
"noremap b - backword
"noremap c - start cutting
"noremap d - delete
"noremap e - to end of word
"noremap f - search rightward for char
"noremap g - many actions
"noremap h - go left
"noremap i - insert
 noremap j jzz
 noremap k kzz
"noremap l - go right
"noremap m - mark
 noremap n nzz
"noremap o - open new line
"noremap p - paste
 noremap q :q<CR>
"noremap r - change one char
"noremap s - start replacing
"noremap t - used by ftplugin/python/jab.vim
"noremap u - undo
 noremap v :noh<cr>
"noremap w - forword
"noremap x - remove char
"noremap y - yank
 noremap yb byw
"noremap z - folds. centering, ...
 noremap zx zo
 noremap zX zO
 noremap zs zR
"noremap zc  
 noremap zd zM 
"
" Punctuation
"
 noremap - $       " I do not like <S-4> meaning end, so I use the key to right of 0
"noremap =
 noremap ] <C-]>   " do this on bufenter
 noremap [ <C-T>   " do this on bufenter
 noremap ; :
 noremap ' @a " play register a
 noremap '' "ap
"noremap \ - leader
 noremap , `
 noremap ,, ``
"noremap . - repeat
"noremap / - search
 noremap // :nohlsearch<cr><c-l>
 noremap /\ :set hlsearch<cr><c-l>
"noremap `
"
" Shifted punctuation
"
"noremap {
"noremap }
"noremap : - command line
"noremap "
"noremap |
"noremap < - 
"noremap > - 
"noremap ? - 
"noremap ~ - 
"noremap !
"noremap @
"noremap L
"noremap $ - 
"noremap %
"noremap ^
"noremap &
"noremap * - 
"noremap (
"noremap )
"noremap _
"noremap +
"
" LETTERS
"
"noremap A - Append
 noremap B :ConqueTerm bash<cr>
"noremap C c$
"noremap D d$
"noremap E e
"noremap F f leftwards
"noremap G
 noremap H :set hlsearch<cr>
"noremap I - Insert
"noremap J - Join lines
nnoremap K <PageUp>zz
"noremap L
"noremap M
 noremap N :noh<cr>
"noremap O - Open line above
"noremap P - paste forward
 noremap Q :qa!<CR>
"noremap R
 noremap S :set nospell<CR>
 noremap T :!tags
"noremap U
"noremap V
 noremap W :wa!<CR>
 noremap X :x!<CR>
"noremap Y
 noremap Z :q!<cr>
"
" ordinary keys 
"     for movement
"
noremap <Space>  <PageDown>zz
noremap <BS>     <PageUp>zz
noremap t<left>  :tabprev<cr>
noremap t<right> :tabnext<cr>
noremap th       :tabprev<cr>
noremap tl       :tabnext<cr>
noremap <S-Tab>  :SeeTab<cr>
noremap <Up> 	 ddkP
noremap <Down>	 ddp
noremap <Left>	 <<
noremap <Right>	 >>
"
" control keys
"
 noremap     <C-d> :qa!<CR>
 noremap     <C-n> :next<CR>
 noremap     <C-p> :prev<CR>
 noremap     <C-q> :qa!<CR>
 noremap     <C-h> <c-w><c-h>
 noremap     <C-j> <c-w><c-j>
 noremap     <C-k> <c-w><c-k>
 noremap     <C-l> <c-w><c-l>
 noremap <C-Right> w
 noremap <C-Left>  b
inoremap     <C-q> <Esc>:qa!<CR>
inoremap <C-Right> <Esc>lwi
inoremap <C-Left>  <Esc>bi
"
" Alt keys
"
 noremap     <A-q>      :qa!<CR>
 noremap <A-Right>      :tabnext<Cr>
 noremap  <A-Left>      :tabprev<Cr>
inoremap     <A-q> <Esc>:qa!<CR>
inoremap <A-Right> <Esc>:tabnext<CR>
inoremap  <A-Left> <Esc>:tabprev<CR>
"
" Leader keys
"
"noremap <leader>a
"noremap <leader>b used by plugin/EasyMotion.vim
"noremap <leader>c 
"noremap <leader>C 
"noremap <leader>d 
"noremap <leader>D 
"noremap <leader>e used by plugin/EasyMotion.vim
"noremap <leader>f used by plugin/EasyMotion.vim
"noremap <leader>g 
"noremap <leader>h
"noremap <leader>i
"noremap <leader>j used by plugin/EasyMotion.vim
"noremap <leader>k used by plugin/EasyMotion.vim
"noremap <leader>l
"noremap <leader>m
 noremap <leader>n :call NumberToggle()<cr>
"noremap <leader>o
"noremap <leader>p
"noremap <leader>q
"noremap <leader>r
 noremap <leader>s :w !sudo tee % >/dev/null<cr>
 noremap <leader>t :call RetabAndStripTrailingWhitespace()<CR> 
"noremap <leader>u
"noremap <leader>v
"noremap <leader>w used by plugin/EasyMotion.vim
"noremap <leader>x
"noremap <leader>y
"noremap <leader>z
"
" Kinda keys
"
set backspace=eol,start,indent
set autoindent smartindent
set matchpairs+=<:>
set listchars=tab:>-,trail:?,eol:$
set tildeop
"
" Screen
"
set background=dark
colorscheme alan-colour
let g:SeeTabGuiFG="Cyan"
set title
if exists('&relativenumber')
	set relativenumber
endif
set showmode " If in Insert, Replace or Visual mode put a message on the last line.
set showcmd  " Show (partial) command in the last line of the screen.
set nowrap
set ts=4
set shiftwidth=4
set noexpandtab
set nospell
"
" Pathogen helps install other vim scipts, see http://github.com/tpope/vim-pathogen
" And it must be set up before the plugin on command (next)
"
call pathogen#infect() 
filetype on
filetype plugin on
filetype indent on

function ChangeBuffer ()
	"
	" diff options
	"
	if &diff
		noremap <buffer> o :diffget<cr>
		noremap <buffer> p :diffput<cr>
		noremap <buffer> ] ]czz
		noremap <buffer> [ [czz
		syntax off
		set diffopt=filler,iwhite
	else
		" noremap ] <C-]>
		" noremap [ <C-T>
		syntax on
	endif
endfunction

autocmd BufEnter * call ChangeBuffer()

"
" diff to when I started editting
"
if !exists(":DiffOrig")
	command DiffOrig vert new | set bt=nofile | r # | 0d_ | diffthis | wincmd p | diffthis
endif
"
" Ok, ok, so I have some spelling blind-spots:
"
abbreviate becuase because
abbreviate seperate separate
"
" Miscellaneous
"
autocmd FileType c,cpp,h,java set cindent
autocmd FileType python compiler pylint
"
" Change numbering automagically
" 	See http://jeffkreeftmeijer.com/2012/relative-line-numbers-in-vim-for-super-fast-movement/
"
function! NumberToggle()
  if(&relativenumber == 1)
    set number
  else
    set relativenumber
  endif
endfunc

autocmd FocusLost * :set number
autocmd FocusGained * :set relativenumber
autocmd InsertEnter * :set number
autocmd InsertLeave * :set relativenumber

"
" From http://items.sjbach.com/319/configuring-vim-right
"
set hidden		" When on a buffer becomes hidden when it is abandoned.
set scrolloff=3	" Minimal number of screen lines to keep above and below the cursor.
set ruler
set shortmess=atI
set visualbell
"
" From http://www.pixelbeat.org/settings/.vimrc
"
set nojoinspaces	" Do not insert two spaces after a '.', '?' and '!' with a join command.
set cursorline		" Highlight the screen line of the cursor with CursorLine
set wildmenu
set wildmode=list:longest,full
"Ignore these files when completing names and in Explorer
set wildignore=.svn,CVS,.git,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.xpm,*.gif,*.py[co]

"
" From http://tim.theenchanter.com/2008/07/crontab-temp-file-must-be-edited-in.html
"	When one of the patterns matches with the name of the file which is written, no backup file is created.
set backupskip=/tmp/*,/private/tmp/*

"
" for searching
"
set ignorecase
set smartcase
set incsearch
set hlsearch
"
" for Tab Completion
"	from vim's help
"
"function! CleverTab()
   "if strpart( getline('.'), 0, col('.')-1 ) =~ '^\s*$'
      "return "\<Tab>"
   "else
      "return "\<C-N>"
"endfunction
"
" and if we need a Tab in the middle of a line: use <S-Tab>
"
function! RetabAndStripTrailingWhitespace()
	:retab!
	:%s/\s\+$//e
endfunction
"
" for history
"
set history=1000
set viminfo=/100,'10,r/mnt/zip,r/mnt/floppy,f0,h,\"100,n~/.viminfo
"
" for filename completion (with Tab)
"
let g:explHideFiles='^\.[^\.],\.gz$,\.exe$,\.zip$,\.py.$,\~$'
let g:explVertical=1
let g:explWinSize=1
let g:explSplitRight=1
let g:explDetailedList=1
let g:explSortBy='date'

let g:netrw_altv = 1
let g:netrw_browse_split = 2
let g:netrw_list_hide='^\.[^\.],\.gz\([^\i]\|$\),\.exe\([^\i]\|$\),\.zip\([^\i]\|$\),\.py[oce],\~\([^\i]\|$\)'
let g:netrw_keepdir=0

let g:jabHideFiles='^\.[^\.],\.gz$,\.exe$,\.zip$,\.py.$,\~$'
let g:jabVertical=1
let g:jabWinSize=1
let g:jabSplitRight=1
let g:jabDetailedList=1
let g:jabSortBy='date'

let g:is_posix = 1

set paste

" Restore my window title
let &titleold="I choose to start one small step now"

" Honour those wee lines at eof
set modeline

" Enable screen swapping, which seems missing in the linux terminfo entry
" help xterm-screens for more info
if &term == "linux"
	set t_ti=[?1049h
	set t_te=[?1049l
endif

