---
paths:

users:
  wwts: ~/.ssh/work
  - builder:
      IdentityFile: ~/.ssh/keys/devops.key
  - ab13173:
      IdentityFile: ~/.ssh/ab13173.key

hosts:
  address: 172.25.32.74
  names:
    twkgit31:
      users:
        - ab13173
    bots:
      users:
        - builder
        - jenkins

Host builder
    Hostname 172.25.32.74
    User builder
    IdentityFile paths.ssh/bots/builder.key

Host jenkins
    Hostname 172.25.32.74
    User jenkins
    IdentityFile paths.ssh/bots/jenkins.key

