#! /bin/bash

# functons for subversion

# sorted by strcmp of function name

# x

# xx

sc () {
	svn ci -m"$@"
}

si () {
	svn_info "$@"
}

sl () {
	svn_log "$@"
}

st () {
	stat "$@"
}

sk () {
	cp $1 ${1}.keep
	svn revert $1
	ls -l $1*
}

sv () {
	[[ -n "$@" ]] && svn revert "$@" || svn revert *
}

# xxx

sdc () {
	svn diff --diff-cmd colordiff "$@"
}

sdh () {
	svn_diff horizontal "$@"
}

sdp () {
	svn_diff python "$@"
}

sdv () {
	svn_diff vertical "$@"
}

stv () {
	shift_dir "$@" && shift
	svn stat $dir | sed -e "s/^ M/svd/" -e "s/^?? /vim /"
}

# xxxx

cocn () {
	svn co -N $1
	cd ${1##*/}
}

cocq () {
	svn co -q $1
	cd ${1##*/}
}

stat () {
	if [[ -z "$1" ]]; then
		rf -q
		do_stat
	else
		for file in "$@"
		do 
			do_stat $file
		done
	fi
}

# xxxxx
# xxxxxx
# xxxxxxx

do_stat () {
	test -n "$1" && path="$1" || path="."
	if [[ -f "$path" || -d "$path" ]]; then
		svn info "$path" > /dev/null && svn stat "$path"
	else echo \"$path\" is not a file, nor dir
	fi
}

statvim () {
	local replacement="$1"
	shift
	if [[ -z "$1" ]]; then
		do_stat | sed -e "s/^M/$replacement/" -e "s/^A/vim/" -e"s/^?/r/"
	else
		for file in "$@"
		do 
			do_stat $file | sed -e "s/^M/$replacement/" -e "s/^A/vim/"
		done
	fi | sort
}

svn_log () {
	if [ -n "$1" ]; then
		if [[ -f $1 || -d $1 ]]; then
			path=$1
			shift 
		fi
	else
		path="."
	fi
	local limit=${1-10}
	svn log -l $limit $path
}

svn_url () {
	test -n "$1" && dir=$1 || dir="."
	local URL=$(svn info $dir | grep URL)
	echo $URL
	SVN_URL=$(echo $URL| sed -e s/[^:]*://)
}

# xxxxxxxx

svn_info () {
	test -n "$1" && dir=$1 || dir="."
	svn info $dir 
}
