#! /bin/bash

BASH_DIR=$(dirname $BASH_SOURCE)

source_here ()
{
    if [[ -n $GITHUB_SOURCES ]]
    then what_source $BASH_DIR/$1 optional
    elif [[ -f $BASH_DIR/$1 ]]
    then source $BASH_DIR/$1
    fi
}

source_here aliases
source_here functons
